apps/admin/urls.py
from django.urls import path
from . import views
from django.views import View
from utils.decorators.user_decorators import my_decorator
from django.utils.decorators import method_decorator
# app的名字
app_name = 'admin'

# @method_decorator(my_decorator)
# def as_view(cls, **initkwargs):
#     return super().as_view(cls, **initkwargs)
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),  # 将这条路由命名为index
    path('tags/', views.TagsManageView.as_view(), name='tags'),
    path('index/',views.index_fn,name='index_fn'),
    path('tags/<int:tag_id>/', views.TagEditView.as_view(), name='tag_edit'),

    path('news/', views.NewsManageView.as_view(), name='news_manage'),
    path('news/<int:news_id>/', views.NewsEditView.as_view(), name='news_edit'),
    path('news/pub/', views.NewsPubView.as_view(), name='news_pub'),
    path('news/images/', views.NewsUploadImage.as_view(), name='upload_image'),
    path('token/', views.UploadToken.as_view(), name='upload_token'),  # 七牛云上传图片需要调用token

    path('hotnews/', views.HotNewsManageView.as_view(), name='hotnews_manage'),
    path('hotnews/<int:hotnews_id>/', views.HotNewsEditView.as_view(), name='hotnews_edit'),
    path('hotnews/add/', views.HotNewsAddView.as_view(), name='hotnews_add'),
    path('tags/<int:tag_id>/news/', views.NewsByTagIdView.as_view(), name='news_by_tagid'),

    path('banners/', views.BannerManageView.as_view(), name='banners_manage'),
    path('banners/<int:banner_id>/', views.BannerEditView.as_view(), name='banners_edit'),
    path('banners/add/', views.BannerAddView.as_view(), name='banners_add'),

    path('docs/', views.DocsManageView.as_view(), name='docs_manage'),
    path('docs/<int:doc_id>/', views.DocsEditView.as_view(), name='docs_edit'),
    path('docs/pub/', views.DocsPubView.as_view(), name='docs_pub'),
    path('docs/files/', views.DocsUploadFile.as_view(), name='upload_text'),

    path('courses/', views.CoursesManageView.as_view(), name='courses_manage'),
    path('courses/<int:course_id>/', views.CoursesEditView.as_view(), name='courses_edit'),
    path('courses/pub/', views.CoursesPubView.as_view(), name='courses_pub'),

    path('groups/', views.GroupsManageView.as_view(), name='groups_manage'),
    path('groups/<int:group_id>/', views.GroupsEditView.as_view(), name='groups_edit'),
    path('groups/add/', views.GroupsAddView.as_view(), name='groups_add'),

    path('users/', views.UsersManageView.as_view(), name='users_manage'),
    path('users/<int:user_id>/', views.UsersEditView.as_view(), name='users_edit'),

    path('usersprofile/', views.UserProfileManageView.as_view(), name='usersprofile_manage'),
    path('usersprofile/<int:user_id>/', views.UsersProfileEditView.as_view(), name='usersprofile_edit'),

]

apps/doc/urls.py
from django.urls import path
from . import views
# app的名字
app_name = 'doc'
urlpatterns = [
    # path('doc_down',views.doc_down,name='doc_down'),
    path('', views.doc_index, name='index'),
    path('<int:doc_id>/', views.DocDownload.as_view(), name='doc_download'),
]

apps/news/urls.py
from django.urls import path
from . import views
# app的名字
app_name = 'news'
urlpatterns = [
    # path('index',views.index,name='index'),
    # path('detail',views.detail,name='detail'),
    # path('search',views.search,name='search'),
    path('', views.IndexView.as_view(), name='index'),  # 将这条路由命名为index
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/banners/', views.NewsBanner.as_view(), name='news_banner'),
    path('news/<int:news_id>', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:news_id>/comments/', views.NewsCommentView.as_view(), name='news_comment'),
    path('search/', views.SearchView(), name='search'),
]

apps/users/urls.py
from django.urls import path
from . import views
# app的名字
app_name = 'users'
urlpatterns = [
    #path('register',views.register,name='register'),
    path('register/',views.RegisterView.as_view(),name='register'),
    # path('login',views.login,name='login')，
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('change/',views.ChangeView.as_view(),name='change')
]

myblog/urls.py
# from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_index
urlpatterns = [
   # path('admin/', admin.site.urls),
   #  path('',home_index),
    path('',include('news.urls')),
    path('users/',include('users.urls')),
    path('course/',include('course.urls')),
    path('docs/',include('doc.urls')),
    path('',include('verifications.urls')),
    path('admin/',include('admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- PC -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
  <meta name="renderer" content="webkit">
  <!-- mobile -->
  <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
  <meta name="author" content="handsomeDawang"/>
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <link rel="stylesheet" href="{% static '/css/base/reset.css' %}">
  <link rel="stylesheet" href="/static/css/base/common.css">
  <link rel="stylesheet" href="/static/css/base/side.css">
  <link rel="stylesheet" href="http://at.alicdn.com/t/font_684044_un7umbuwwfp.css">
  <link rel="stylesheet" href="/static/css/authPro/auth.css">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
  <!-- css link start -->
  {% block link %}
  {% endblock %}
  <!-- css link end -->
  <!-- script src start -->
  {% block script_head %}
  {% endblock %}
  <!-- script src end -->
</head>
<body>
<!-- header start -->
<header id="header">
  <div class="mw1200 header-contain clearfix">
    <!-- logo start -->
    <h1 class="logo">
      <a href="{% url 'news:index' %}" class="logo-title">Python</a>
    </h1>
    <!-- logo end -->
    <!-- nav start -->
    <nav class="nav">
      <ul class="menu" data-navid="{{ navId }}">
        <li><a href="{% url 'news:index' %}">首页</a></li>
        <li><a href="{% url 'course:index'%}">在线课堂</a></li>
        <li><a href="{% url 'doc:index' %}" target="_blank">下载文档</a></li>
        <li><a href="{% url 'news:search' %}">搜索</a></li>
      </ul>
    </nav>
    <!-- nav end -->
    <!-- login start -->
    <div class="login-box">
          <!-- is_authenticated request -->
        {% if user.is_authenticated %}
          <div class="author">
              <i class="PyWhich py-user"></i>
              <span>{{ user.username }}</span>
              <ul class="author-menu">
                {% if user.is_staff %}
                  <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                {% endif %}
                  <li><a href="{% url 'users:logout' %}">退出登录</a></li>
              </ul>
          </div>
        {% else %}
          <div>
              <i class="PyWhich py-user"></i>
              <span>
                  <a href="{% url 'users:login' %}" class="login">登录</a> / <a href="{% url 'users:register' %}"
                                                                          class="reg">注册</a>
              </span>
          </div>
        {% endif %}
          <div class="author hide">
              <i class="PyWhich py-user"></i>
              <span>qwertyui</span>
              <ul class="author-menu">
                  <li><a href="javascript:void(0);">后台管理</a></li>
                  <li><a href="{% url 'users:logout' %}">退出登录</a></li>
              </ul>
          </div>
      </div>
    <!-- login end -->
  </div>
</header>
<!-- header end -->
<!-- main start -->
{% block main_start %}
<main id="main">
  <div class="w1200 clearfix">
    <!-- main-contain start  -->
    {% block main_contain %}

    {% endblock %}
    <!-- main-contain  end -->

    {% block side %}
    <!-- side start -->
      <aside class="side">
          <div class="side-activities">
              <h3 class="activities-title">在线课堂<a href="javascript:void(0)">更多</a></h3>
              <div class="activities-img">
                  <a href="javascript:void(0);" target="_blank">
                      <img src="../../static/images/english.jpg" alt="title">
                  </a>
                  <p class="activities-tips">对话国外小姐姐</p>
              </div>
              <ul class="activities-list">
                  <li>
                      <a href="javascript:void(0);" target="_blank">
                          <span class="active-status active-start">报名中</span>
                          <span class="active-title"><a
                                  href="https://www.shiguangkey.com/course/2432"> Django 项目班</a></span>
                      </a>
                  </li>
                  <li>
                      <a href="javascript:void(0);" target="_blank">
                          <span class="active-status active-end">已结束</span>
                          <span class="active-title"><a
                                  href="https://www.shiguangkey.com/course/2321">Python入门基础班</a></span>
                      </a>
                  </li>
              </ul>
          </div>
          <div class="side-attention clearfix">
              <h3 class="attention-title">关注我</h3>
              <ul class="side-attention-address">
                  <li>
                      <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-GitHub"></i>Youkou</a>
                  </li>
                  <li>
                      <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-zhihu"
                                                                       style="color:rgb(0, 108, 226);"></i>Youkou</a>
                  </li>
                  <li>
                      <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-weibo"
                                                                       style="color:rgb(245,92,110);"></i>Youkou</a>
                  </li>
              </ul>
              <div class="side-attention-qr">
                  <p>扫码关注</p>
              </div>
          </div>

        {% block hot_recommend %}
          <div class="side-hot-recommend">
              <h3 class="hot-recommend">热门推荐</h3>
              <ul class="hot-news-list">

                  <li>
                      <a href="javascript:void(0)" class="hot-news-contain clearfix">
                          <div class="hot-news-thumbnail">
                              <img src="../../static/images/python_web.jpg"
                                   alt="">
                          </div>
                          <div class="hot-news-content">
                              <p class="hot-news-title">Django调试工具django-debug-toolbar安装使用教程</p>
                              <div class="hot-news-other clearfix">
                                  <span class="news-type">python框架</span>
                                  <!-- 自带的 -->
                                  <time class="news-pub-time">11月11日</time>
                                  <span class="news-author">python</span>
                              </div>
                          </div>
                      </a>
                  </li>

              </ul>
          </div>
        {% endblock %}

      </aside>
    <!-- side end -->
    {% endblock %}

  </div>
</main>
<!-- main end -->
{% endblock %}
<!-- footer start -->
<footer id="footer">
    <div class="footer-box">
        <div class="footer-content">
            <p class="top-content">
					<span class="link">
						<a href="javascript:void(0)">关于Python</a> |
						<a href="javascript:void(0)">我就是我</a> |
						<a href="javascript:void(0)">人生苦短</a> |
						<a href="javascript:void(0)">我用Python</a>
					</span>
                <span class="about-me">关于我: <i class="PyWhich py-wechat"></i> Dawang</span>
            </p>
            <p class="bottom-content">
                <span>地址： xxxx</span>
                <span>联系方式: <a href="tel:400-1567-315">400-1567-315</a> (24小时在线)</span>
            </p>
        </div>
        <p class="copyright-desc">
            Copyright &copy; 2008 - 2018 xxx有限公司. All Rights Reserved
        </p>
    </div>
</footer>
<!-- footer end -->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="/static/js/base/common.js"></script>
<script src="/static/js/base/message.js"></script>
{% block script %}
{% endblock %}
</body>
</html>