apps/news/urls.py
from django.urls import path
from . import views
# app的名字
app_name = 'news'
urlpatterns = [
    # path('index',views.index,name='index'),
    # path('detail',views.detail,name='detail'),
    # path('search',views.search,name='search'),
    path('', views.IndexView.as_view(), name='index'),  # 将这条路由命名为index
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/banners/', views.NewsBanner.as_view(), name='news_banner'),
    path('news/<int:news_id>', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:news_id>/comments/', views.NewsCommentView.as_view(), name='news_comment'),
    path('search/', views.SearchView(), name='search'),
]

myblog/urls.py
# from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_index
urlpatterns = [
   # path('admin/', admin.site.urls),
   #  path('',home_index),
    path('',include('news.urls')),
    path('users/',include('users.urls')),
    path('course/',include('course.urls')),
    path('docs/',include('doc.urls')),
    path('',include('verifications.urls')),
    path('admin/',include('admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/models.py
from django.db import models
from utils.models import ModelBase
# Create your models here.

class Tag(ModelBase):
    """
    create news tag model
    """
    name = models.CharField(max_length=64, verbose_name="标签名", help_text="标签名")
    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_tag"  # 指明数据库表名
        verbose_name = "新闻标签"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称
    def __str__(self):
        return self.name
class News(ModelBase):
    """
    create news model
    """
    title = models.CharField(max_length=150, verbose_name="标题", help_text="标题")
    digest = models.CharField(max_length=200, verbose_name="摘要", help_text="摘要")
    content = models.TextField(verbose_name="内容", help_text="内容")
    clicks = models.IntegerField(default=0, verbose_name="点击量", help_text="点击量")
    image_url = models.URLField(default="", verbose_name="图片url", help_text="图片url")
    #on_delete 多为子，一为主
    #CASCADE  主表删除 子表跟着删除
    #PROTECT  主表删除  抛 PROTECTerror异常
    #SET_NULL   主表删除字段  子表为null
    #SET_DEFAULT 主表删除字段  子表指定默认设定的
    #SET（） 括号里可以是函数，设置为自己定义的东西
    #DO_NOTHING  字面意思 啥也不干
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)
    class Meta:
        ordering = ['-update_time', '-id']#默认排序 update_time 倒序DESC 正序ASC
        db_table = "tb_news"  # 指明数据库表名
        verbose_name = "新闻"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称
    def __str__(self):
        return self.title
class Comments(ModelBase):
    """
    create news comment model
    """
    content = models.TextField(verbose_name="内容", help_text="内容")
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)
    news = models.ForeignKey('News', on_delete=models.CASCADE)
    parents = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True)
    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_comments"  # 指明数据库表名
        verbose_name = "评论"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称
    def __str__(self):
        return '<评论{}>'.format(self.id)

    def to_dict_data(self):
        comment_dict = {
            'news_id': self.news.id,
            'content_id': self.id,
            'content': self.content,
            'author': self.author.username,
            'update_time': self.update_time.strftime('%Y年%m月%d日 %H:%M'),
            'parents_id': self.parents.to_dict_data() if self.parents else None,
        }

        return comment_dict
class HotNews(ModelBase):
    """
    creat hotnews model
    """
    PRI_CHOICES = [
        (1,'第一级'),
        (2,'第二级'),
        (3,'第三级')
    ]
    news = models.OneToOneField('News', on_delete=models.CASCADE)
    priority = models.IntegerField(choices=PRI_CHOICES,default=3,verbose_name="优先级", help_text="优先级")
    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_hotnews"  # 指明数据库表名
        verbose_name = "热门新闻"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称
    def __str__(self):
        return '<热门新闻{}>'.format(self.id)
class Banner(ModelBase):
    """
    create news banner model
    """
    PRI_CHOICES = [
        (1,'第一级'),
        (2,'第二级'),
        (3,'第三级'),
        (4,'第四级'),
        (5,'第五级'),
        (6,'第六级'),
    ]
    image_url = models.URLField(verbose_name="轮播图url", help_text="轮播图url")
    priority = models.IntegerField(choices=PRI_CHOICES,default=6,verbose_name="优先级", help_text="优先级")
    news = models.OneToOneField('News', on_delete=models.CASCADE)
    class Meta:
        ordering = ['priority', '-update_time', '-id']
        db_table = "tb_banner"  # 指明数据库表名
        verbose_name = "轮播图"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称
    def __str__(self):
        return '<轮播图{}>'.format(self.id)

apps/news/views.py
import logging
import json
from django.shortcuts import render,HttpResponse
from django.http import Http404
from django.views import View
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from . import models
from . import constants
from utils.json_fun import to_json_data
from utils.res_code import Code,error_map
from myblog import settings
# Create your views here.
# 导入日志器
logger = logging.getLogger('django')
# def index(request):
#     """
#     index page
#     :param request:
#     :return:
#     """
#     return render(request,'news/index.html')
# def detail(request):
#     return render(request,'news/news_detail.html')
# def search(request):
#     return render(request,'news/search.html')
class IndexView(View):
    """
    create news view
    render tags hot_news
    """
    def get(self, request):
        """
        create index page view
        """
        tags = models.Tag.objects.only('id', 'name').filter(is_delete=False)
        hot_news = models.HotNews.objects.select_related('news').only('news__title', 'news__image_url',
                                                                      'news__id').filter(is_delete=False).order_by(
            'priority', '-news__clicks')[0:constants.SHOW_HOTNEWS_COUNT]
        context = {
            'tags':tags,
            'hot_news':hot_news,
            'navId' : 0
        }
        navId = 0
        return render(request, 'news/index.html', locals())
#1.创建类视图
#2.校验参数
#3.从数据库中查询新闻列表数据
#4.序列化数据
#5.返回给前端
class NewsListView(View):
    """
    create news list view
    route :/news/
    """
    def get(self, request):
        print(request)
        try:
            tag_id = int(request.GET.get('tag_id', 0))
        except Exception as e:
            logger.error("标签错误：\n{}".format(e))
            tag_id = 0
        try:
            page = int(request.GET.get('page', 1))
        except Exception as e:
            logger.error("当前页数错误：\n{}".format(e))
            page = 1

        news_queryset = models.News.objects.select_related('tag', 'author'). \
            only('id','title', 'digest', 'image_url', 'update_time', 'tag__name', 'author__username')

        # if models.Tag.objects.only('id').filter(is_delete=False, id=tag_id).exists():
        # news = news_queryset.filter(is_delete=False, tag_id=tag_id)
        # else:
        # news = news_queryset.filter(is_delete=False)
        news = news_queryset.filter(is_delete=False, tag_id=tag_id) or \
               news_queryset.filter(is_delete=False)
        paginator = Paginator(news, constants.PER_PAGE_NEWS_COUNT)
        try:
            news_info = paginator.page(page)
        except EmptyPage:
            # 若用户访问的页数大于实际页数，则返回最后一页数据
            logging.info("用户访问的页数大于总页数。")
            news_info = paginator.page(paginator.num_pages)

        # 4.序列化输出
        news_info_list = []
        for n in news_info:
            news_info_list.append({
                'id': n.id,
                'title': n.title,
                'digest': n.digest,
                'image_url': n.image_url,
                'tag_name': n.tag.name,
                'author': n.author.username,
                'update_time': n.update_time.strftime('%Y年%m月%d日 %H:%M'),

            })

        # 5.创建返回给前端的数据
        data = {
            'total_pages': paginator.num_pages,
            'news': news_info_list
        }
        # print(data)
        return to_json_data(data=data)

class NewsBanner(View):
    """
    create news banner model
    router:/news/banners/
    """
    def get(self, request):
        banners = models.Banner.objects.select_related('news').only('image_url', 'news__id', 'news__title').\
            filter(is_delete=False)[0:constants.SHOW_BANNER_COUNT]

        # 序列化输出
        banners_info_list = []
        for b in banners:
            banners_info_list.append({
                'image_url': b.image_url,
                'news_id': b.news.id,
                'news_title': b.news.title,
            })

        # 创建返回给前端的数据
        data = {
            'banners': banners_info_list
        }

        return to_json_data(data=data)

class NewsDetailView(View):
    """
    create news detail view
    router：/news/<int:news_id>/
    """
    # /* 为文章内容添加样式 */
    # 在templates/news1/news_detail.html文件中需要添加如下内容：
    # .news-content p {
    # 	font-size: 16px;
    # 	line-height: 26px;
    # 	text-align: justify;
    # 	word-wrap: break-word;
    # 	padding: 3px 0
    # }
    def get(self, request, news_id):
        news = models.News.objects.select_related('tag', 'author'). \
            only('title', 'content', 'update_time', 'tag__name', 'author__username').\
            filter(is_delete=False, id=news_id).first()
        if news:
            comments = models.Comments.objects.select_related('author', 'parents').\
                only('content', 'author__username', 'update_time',
                     'parents__author__username', 'parents__content', 'parents__update_time').\
                filter(is_delete=False, news_id=news_id)

            # 序列化输出
            comments_list = []
            # 迭代之后开始去数据库查
            for comm in comments:
                comments_list.append(comm.to_dict_data())
            comments_count = len(comments_list)
            return render(request, 'news/news_detail.html', locals())
        else:
            raise Http404("<新闻{}>不存在😢".format(news_id))
            # return Http404('<h1>Page not found</h1>')
            #return HttpResponseNotFound('<h1>Page not found</h1>')
class NewsCommentView(View):
    """
     create newscomments detail view
        router：news/<int:news_id>/comments/
    """
    # print('2222')
    def post(self, request, news_id):
        # print('111111', request)
        if not request.user.is_authenticated:
            return to_json_data(errno=Code.SESSIONERR, errmsg=error_map[Code.SESSIONERR])

        if not models.News.objects.only('id').filter(is_delete=False, id=news_id).exists():
            return to_json_data(errno=Code.PARAMERR, errmsg="新闻不存在！")

        # 从前端获取参数
        try:
            json_data = request.body
            # print('111111',json_data)
            if not json_data:
                return to_json_data(errno=Code.PARAMERR, errmsg="参数为空，请重新输入！")
            # 将json转化为dict
            dict_data = json.loads(json_data.decode('utf8'))
        except Exception as e:
            logger.info('错误信息：\n{}'.format(e))
            return to_json_data(errno=Code.UNKOWNERR,errmsg=error_map[Code.UNKOWNERR])
        content = dict_data.get('content')
        if not content:
            return to_json_data(errno=Code.PARAMERR, errmsg="评论内容不能为空！")

        parents_id = dict_data.get('parents_id')
        try:
            if parents_id:
                parent_id = int(parents_id)
                if not models.Comments.objects.only('id'). \
                        filter(is_delete=False, id=parents_id, news_id=news_id).exists():
                    return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])

        except Exception as e:
            logging.info("前端传过来的parents_id异常：\n{}".format(e))
            return to_json_data(errno=Code.PARAMERR, errmsg="未知异常")

        # 保存到数据库
        new_content = models.Comments()
        new_content.content = content
        new_content.news_id = news_id
        new_content.author = request.user
        new_content.parents_id = parents_id if parents_id else None
        new_content.save()

        return to_json_data(data=new_content.to_dict_data())
from haystack.views import SearchView as _SearchView


class SearchView(_SearchView):
    # 模版文件
    template = 'news/search.html'

    # 重写响应方式，如果请求参数q为空，返回模型News的热门新闻数据，否则根据参数q搜索相关数据
    def create_response(self):
        kw = self.request.GET.get('q', '')
        if not kw:
            show_all = True
            hot_news = models.HotNews.objects.select_related('news'). \
                only('news__title', 'news__image_url', 'news__id'). \
                filter(is_delete=False).order_by('priority', '-news__clicks')

            paginator = Paginator(hot_news, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE)
            try:
                page = paginator.page(int(self.request.GET.get('page', 1)))
            except PageNotAnInteger:
                # 如果参数page的数据类型不是整型，则返回第一页数据
                page = paginator.page(1)
            except EmptyPage:
                # 用户访问的页数大于实际页数，则返回最后一页的数据
                page = paginator.page(paginator.num_pages)
            navId = 3
            return render(self.request, self.template, locals())
        else:
            show_all = False
            qs = super(SearchView, self).create_response()
            return qs

templates/news/news_detail.html
{% extends 'base/base.html' %}
{% block title %}
新闻详情页
{% endblock %}
{% block link %}
    <link rel="stylesheet" href="/static/css/news/news-detail.css">
{% endblock %}
{% block script_head %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}
<body>
<!-- header start -->
<!-- header end -->
<!-- main start -->
{% block main_start %}
  <main id="main">
  <div class="w1200 clearfix">
    <!-- news-contain start  -->
     <div class="news-contain">
      <h1 class="news-title">{{ news.title }}</h1>
      <div class="news-info">
        <div class="news-info-left">
          <span class="news-author">{{ news.author.username }}</span>
          <span class="news-pub-time">{{ news.update_time }}</span>
          <span class="news-type">{{ news.tag.name }}</span>
        </div>
      </div>
      <article class="news-content">
        {{ news.content|safe }}
      </article>
      <div class="comment-contain">
        <div class="comment-pub clearfix">
          <div class="new-comment">
            文章评论(<span class="comment-count">{{ comments_count }}</span>)
          </div>
          {% if user.is_authenticated %}
              <div class="comment-control logged-comment" news-id="{{ news.id }}">
                <input type="text" placeholder="请填写评论">
                <button class="comment-btn">发表评论</button>
              </div>
          {% else %}
              <div class="comment-control please-login-comment" news-id="{{ news.id }}">
                <input type="text" placeholder="请登录后参加评论" readonly>
                <button class="comment-btn">发表评论</button>
              </div>
          {% endif %}
        </div>
        <ul class="comment-list">
          {% for one_comment in comments_list %}
            <li class="comment-item">
                <div class="comment-info clearfix">
                  <img src="{% static 'images/avatar.jpeg' %}" alt="avatar" class="comment-avatar">
                  <span class="comment-user">{{ one_comment.author }}</span>
                  <span class="comment-pub-time">{{ one_comment.update_time }}</span>
                </div>
                <div class="comment-content">{{ one_comment.content }}</div>
                {% if one_comment.parents_id %}
                      <div class="parent_comment_text">
                          <p>回复：</p>
                          <div class="parent_content_text">{{ one_comment.parents_id.content }}</div>
                          <br/>
                          <div class="parent_username">{{ one_comment.parents_id.author }} &nbsp {{ one_comment.parents_id.update_time }}</div>
                      </div>
                {% endif %}
                <div class="comment_time left_float">{{ one_comment.update_time }}</div>
                <a href="javascript:void(0);" class="reply_a_tag right_float">回复</a>
                <form class="reply_form left_float" comment-id="{{ one_comment.content_id }}" news-id="{{ one_comment.news_id }}">
                    <textarea class="reply_input"></textarea>
                    <input type="button" value="回复" class="reply_btn right_float">
                    <input type="reset" name="" value="取消" class="reply_cancel right_float">
                </form>
            </li>
          {% endfor %}
        </ul>
      </div>

    </div>
    <!-- news-contain end  -->
    <!-- side start -->
    {% block side %}
        {{ block.super }}
    {% endblock %}
    <!-- side end -->
  </div>
</main>
{% endblock %}
<!-- main end -->
<!-- footer start -->
<!-- footer end -->
{% block script %}
  <script src="{% static 'js/news/news_detail.js' %}"></script>
{% endblock %}

templates/news/search.html
{% extends 'base/base.html' %}
{% block link %}
  <link rel="stylesheet" href="../../static/css/news/search.css">
{% endblock %}
{% block title %}
  搜索
{% endblock %}
    <body>
       <!-- header start -->
        <!-- header end -->
       <!-- main start -->
       {% block main_start %}
         <main id="main">
           <div class="w1200 clearfix">
               <!-- main-contain start  -->
               <div class="main-contain ">
                   <!-- search-box start -->
                   <div class="search-box">
                       <form action="" style="display: inline-flex;">
                           <input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control">
                           <input type="submit" value="搜索" class="search-btn">
                       </form>
                       <!-- 可以用浮动 垂直对齐 以及 flex  -->
                   </div>
                   <!-- search-box end -->
                   <!-- content start -->
                   <div class="content">
                       <!-- search-list start -->
                      {% if not show_all %}
                          <div class="search-result-list">
                            <h2 class="search-result-title">
                              搜索结果 <span style="font-weight: 700;color: #ff6620;">{{ paginator.num_pages }}</span>页
                            </h2>
                            <ul class="news-list">
                              {# 导入自带高亮功能 #}
                              {% load highlight %}
                              {% for one_news in page.object_list %}
                                <li class="news-item clearfix">
                                  <a href="{% url 'news:news_detail' one_news.id %}" class="news-thumbnail" target="_blank">
                                  <img src="{{ one_news.object.image_url }}">
                                  </a>
                                  <div class="news-content">
                                    <h4 class="news-title">
                                      <a href="{% url 'news:news_detail' one_news.id %}">
                                        {% highlight one_news.title with query %}
                                      </a>
                                    </h4>
                                    <p class="news-details">{{ one_news.digest }}</p>
                                    <div class="news-other">
                                      <span class="news-type">{{ one_news.object.tag.name }}</span>
                                      <span class="news-time">{{ one_news.object.update_time }}</span>
                                      <span
                                          class="news-author">{% highlight one_news.object.author.username with query %}

                                      </span>
                                    </div>
                                  </div>
                                </li>
                              {% endfor %}
                            </ul>
                          </div>
                        {% else %}
                        <div class="news-contain">
                           <div class="hot-recommend-list">
                               <h2 class="hot-recommend-title">热门推荐</h2>
                               <ul class="news-list">
                                 {% for one_hotnews in page.object_list %}

                                  <li class="news-item clearfix">
                                    <a href="#" class="news-thumbnail">
                                      <img src="{{ one_hotnews.news.image_url }}">
                                    </a>
                                    <div class="news-content">
                                      <h4 class="news-title">
                                        <a href="{% url 'news:news_detail' one_hotnews.news.id %}">{{ one_hotnews.news.title }}</a>
                                      </h4>
                                      <p class="news-details">{{ one_hotnews.news.digest }}</p>
                                      <div class="news-other">
                                        <span class="news-type">{{ one_hotnews.news.tag.name }}</span>
                                        <span class="news-time">{{ one_hotnews.update_time }}</span>
                                        <span class="news-author">{{ one_hotnews.news.author.username }}</span>
                                      </div>
                                    </div>
                                  </li>

                                {% endfor %}

                               </ul>
                           </div>
                       </div>
                   {% endif %}
                       <!-- search-list end -->
                       <!-- news-contain start -->
                         {# 分页导航 #}
                     <div class="page-box" id="pages">
                       <div class="pagebar" id="pageBar">
                          <a class="a1">{{ page.paginator.count }}条</a>
                         {# 上一页的URL地址 #}
                         {% if page.has_previous %}
                           {% if query %}
                             <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.previous_page_number }}"
                                class="prev">上一页</a>
                           {% else %}
                             <a href="{% url 'news:search' %}?page={{ page.previous_page_number }}" class="prev">上一页</a>
                           {% endif %}
                         {% endif %}
                         {# 列出所有的URL地址 #}
                         {% for num in page.paginator.page_range|slice:":10" %}
                           {% if num == page.number %}
                             <span class="sel">{{ page.number }}</span>
                           {% else %}
                             {% if query %}
                               <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ num }}"
                                  target="_self">{{ num }}</a>
                             {% else %}
                               <a href="{% url 'news:search' %}?page={{ num }}" target="_self">{{ num }}</a>
                             {% endif %}
                           {% endif %}
                         {% endfor %}

                        {# 如果页数大于10，则打两点 #}
                         {% if page.paginator.num_pages > 10 %}
                           ..

                           {% if query %}
                             <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.paginator.num_pages }}"
                                target="_self">{{ page.paginator.num_pages }}</a>
                           {% else %}
                             <a href="{% url 'news:search' %}?page={{ page.paginator.num_pages }}"
                                target="_self">{{ page.paginator.num_pages }}</a>
                           {% endif %}

                         {% endif %}

                         {# 下一页的URL地址 #}
                         {% if page.has_next %}
                           {% if query %}
                             <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.next_page_number }}"
                                class="next">下一页</a>
                           {% else %}
                             <a href="{% url 'news:search' %}?page={{ page.next_page_number }}" class="next">下一页</a>
                           {% endif %}
                         {% endif %}
                       </div>
                     </div>

                       <!-- news-contain end -->
                   </div>
                   <!-- content end -->
               </div>
               <!-- main-contain  end -->
               <!-- side start -->
               {% block side %}
                  {{ block.super }}
               {% endblock %}
               <!-- side end -->
           </div>
       </main>
       {% endblock %}
       <!-- main end -->
       <!-- footer start -->
       <!-- footer end -->
       {% block script %}
         <script src="../../static/js/common.js"></script>
         <script src="../../static/js/index.js"></script>
       {% endblock %}