apps/users/urls.py
from django.urls import path
from . import views
# app的名字
app_name = 'users'
urlpatterns = [
    #path('register',views.register,name='register'),
    path('register/',views.RegisterView.as_view(),name='register'),
    # path('login',views.login,name='login')，
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('change/',views.ChangeView.as_view(),name='change')
]

myblog/urls.py
# from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_index
urlpatterns = [
   # path('admin/', admin.site.urls),
   #  path('',home_index),
    path('',include('news.urls')),
    path('users/',include('users.urls')),
    path('course/',include('course.urls')),
    path('docs/',include('doc.urls')),
    path('',include('verifications.urls')),
    path('admin/',include('admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser,UserManager as _UserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from utils.models import ModelBase
# Create your models here.
class UserManager(_UserManager):
    """
    define user manager for modifing 'no need email'
    when 'python manager.py createsuperuser '

    """

    def create_superuser(self, username, password, email=None, **extra_fields):
        super(UserManager, self).create_superuser(username=password,
                                                  password=password, email=email, **extra_fields)
class Users(AbstractUser):
    """
    add mobile/email_active fields to Django users modules
    """
    objects = UserManager()
    # A list of the field names that will be prompted for
    # when creating a user via the createsuperuser management command.
    REQUIRED_FIELDS = ['mobile']
    # help_text在api接口文档中会用到
    # verbose_name在admin站点中会用到
    mobile = models.CharField(max_length=11,unique=True,help_text="手机号",verbose_name="手机号",
                              error_messages={
                                  'unique':"此手机号已经注册",
                              },)
    email_active = models.BooleanField(default=False,verbose_name="邮箱验证状态")
    #源数据信息
    class Meta:
        #数据表
        db_table = 'tb_users'# 指明数据库表名
        verbose_name = '用户'# 在admin站点中显示的名称
        #显示的复数名称
        verbose_name_plural = verbose_name

    def get_groups_name(self):
        groups_name_list = [i.name for i in self.groups.all()]
        # 列表转字符串 通常用join方法 而非用 + 可迭代对象都可以用join方法
        return '|'.join(groups_name_list)#

    # 打印对象时调用
    def __str__(self):
        return self.username

class UsersProfile(ModelBase):
    """create users profile model
    """
    GENDER_CHOICES = (
        ('M', '男'),
        ('F', '女'),
    )
    user = models.OneToOneField(Users, on_delete=models.CASCADE, related_name='user_profile')
    nickname = models.TextField(max_length=100, null=True, blank=True)
    born_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    motto = models.TextField(max_length=1024, null=True, blank=True)

    class Meta:
        #数据表
        db_table = 'tb_users_profile'# 指明数据库表名
        verbose_name = '用户个人信息'# 在admin站点中显示的名称
        #显示的复数名称
        verbose_name_plural = verbose_name

@receiver(post_save,sender=Users)
def create_user_profile(sender,**kwargs):
    """
        create user profile function
    """
    if kwargs.get('created',False):
        user_profile = UsersProfile.objects.get_or_create(user=kwargs.get('instance'))
        if user_profile[-1]:
            user_profile = user_profile[0]
            user_profile.nickname = '老李'
            user_profile.born_date = datetime.date(1980,11,11)
            user_profile.motto = '老李出马，一个顶两'
            user_profile.save()

apps/users/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
  @Time : 2018/12/8 2:22 PM
  @Auth : Youkou
  @Site : www.youkou.site
  @File : forms.py
  @IDE  : PyCharm
  @Edit : 2018/12/8
-------------------------------------------------
"""
import re

from django import forms
from django.db.models import Q
from django_redis import get_redis_connection
from django.contrib.auth import login,logout

from verifications.constants import SMS_CODE_NUMS
from .models import Users
from . import constants
class RegisterForm(forms.Form):
    """
    """
    username = forms.CharField(label='用户名', max_length=20, min_length=5,
                               error_messages={"min_length": "用户名长度要大于5", "max_length": "用户名长度要小于20",
                                               "required": "用户名不能为空"}
                               )
    password = forms.CharField(label='密码', max_length=20, min_length=6,
                               error_messages={"min_length": "密码长度要大于6", "max_length": "密码长度要小于20",
                                               "required": "密码不能为空"}
                               )
    password_repeat = forms.CharField(label='确认密码', max_length=20, min_length=6,
                                      error_messages={"min_length": "密码长度要大于6", "max_length": "密码长度要小于20",
                                                      "required": "密码不能为空"}
                                      )
    mobile = forms.CharField(label='手机号', max_length=11, min_length=11,
                             error_messages={"min_length": "手机号长度有误", "max_length": "手机号长度有误",
                                             "required": "手机号不能为空"})

    sms_code = forms.CharField(label='短信验证码', max_length=SMS_CODE_NUMS, min_length=SMS_CODE_NUMS,
                               error_messages={"min_length": "短信验证码长度有误", "max_length": "短信验证码长度有误",
                                               "required": "短信验证码不能为空"})
    route_id = forms.CharField(label='路由id')

    def clean_mobile(self):
        """
        check mobile
        :return:
        """
        tel = self.cleaned_data.get('mobile')
        # route_id = self.cleaned_data.get('route_id')
        # username = self.cleaned_data.get('username')
        # print(2,tel,route_id,username)
        if not re.match(r"^1[3-9]\d{9}$", tel):
            raise forms.ValidationError("手机号码格式不正确")

        # if Users.objects.filter(mobile=tel).exists():
        #     raise forms.ValidationError("手机号已注册，请重新输入！")

        return tel

    def clean(self):
        """
        check whether the two passwords are the same,and check whether the sms_code is correct.
        :return:
        """
        #1.获取参数
        cleaned_data = super().clean()
        passwd = cleaned_data.get('password')
        passwd_repeat = cleaned_data.get('password_repeat')
        #2.判断两次输入的密码是否一致
        if passwd != passwd_repeat:
            raise forms.ValidationError("两次密码不一致")

        #3.判断短信验证码是否正确
        tel = cleaned_data.get('mobile')
        sms_text = cleaned_data.get('sms_code')
        #route_id = cleaned_data.get('route_id')
        #print(1,route_id)
        # 建立redis连接
        redis_conn = get_redis_connection(alias='verify_codes')
        #创建保存短信验证码的标记key
        sms_fmt = "sms_{}".format(tel).encode('utf-8')
        #
        real_sms = redis_conn.get(sms_fmt)
        #print(real_sms)
        #print(real_sms.decode('utf-8'),sms_text)
        #
        if (not real_sms) or (sms_text != real_sms.decode('utf-8')):
            raise forms.ValidationError("短信验证码错误")

class LoginForm(forms.Form):
    """
    login form data
    """
    user_account = forms.CharField()
    password = forms.CharField(label='密码', max_length=20, min_length=6,
                               error_messages={"min_length": "密码长度要大于6", "max_length": "密码长度要小于20",
                                               "required": "密码不能为空"})
    remember_me = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        """
        :param args:
        :param kwargs:
        构造request 参数 帮助传参 设置session
        """
        self.request = kwargs.pop('request', None)#pop 没有 返回None
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean_user_account(self):
        """
        初始校验
        """
        user_info = self.cleaned_data.get('user_account')
        if not user_info:
            raise forms.ValidationError("用户账号不能为空")

        if not re.match(r"^1[3-9]\d{9}$", user_info) and (len(user_info) < 5 or len(user_info) > 20):
            raise forms.ValidationError("用户账号格式不正确，请重新输入")

        return user_info

    def clean(self):
        """
        查询数据库 检查数据 实现登录
        """
        cleaned_data = super().clean()
        # 1.获取清洗之后的用户账号
        user_info = cleaned_data.get('user_account')
        # 2. 获取清洗之后的用户密码
        passwd = cleaned_data.get('password')
        hold_login = cleaned_data.get('remember_me')

        # 在form表单中实现登录逻辑
        #3.查询数据库，判断用户账号和密码是否正确
        user_queryset = Users.objects.filter(Q(mobile=user_info) | Q(username=user_info))
        if user_queryset:
            user = user_queryset.first()
            if user.check_password(passwd):
                if hold_login:  # 在redis中保存session信息
                    self.request.session.set_expiry(constants.USER_SESSION_EXPIRES)
                    #None 如果value是None,session会依赖全局session失效策略 为两周过期 constants.USER_SESSION_EXPIRES 5天
                else:
                    self.request.session.set_expiry(0)
                    #如果value是0,用户关闭浏览器session就会失效。如果value是个datatime或timedelta，session就会在这个时间后失效。
                login(self.request, user)
            else:
                raise forms.ValidationError("密码不正确，请重新输入")
        #4.查询结果返回
        else:
            raise forms.ValidationError("用户账号不存在，请重新输入")

class ChangeForm(forms.Form):
    """
    check password form data
    """
    user_account = forms.CharField()
    password = forms.CharField(label='密码', max_length=20, min_length=6,
                               error_messages={"min_length": "密码长度要大于6", "max_length": "密码长度要小于20",
                                               "required": "密码不能为空"})

    def clean_user_account(self):
        """
        初始校验
        """
        user_info = self.cleaned_data.get('user_account')
        if not user_info:
            raise forms.ValidationError("用户账号不能为空")

        if not re.match(r"^1[3-9]\d{9}$", user_info) and (len(user_info) < 5 or len(user_info) > 20):
            raise forms.ValidationError("用户账号格式不正确，请重新输入")

        return user_info

    def clean(self):
        """
        查询数据库 检查数据 实现登录
        """
        cleaned_data = super().clean()
        # 1.获取清洗之后的用户账号
        user_info = cleaned_data.get('user_account')
        # 2. 获取清洗之后的用户密码
        passwd = cleaned_data.get('password')
        #3.查询数据库，判断用户账号和密码是否正确
        user_queryset = Users.objects.filter(Q(mobile=user_info) | Q(username=user_info))
        if user_queryset:
            user = user_queryset.first()
            if not user.check_password(passwd):
                raise forms.ValidationError("密码不正确，请重新输入")
        #4.查询结果返回
        else:
            raise forms.ValidationError("用户账号不存在，请重新输入")

apps/users/views.py
import json
import logging
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.contrib.auth import login,logout
from django.db.models import Q

from .forms import RegisterForm,LoginForm
from .models import Users
from utils.json_fun import to_json_data
from utils.res_code import Code, error_map
#导包顺序  PEP8 规范  内置的包 》 Django的包 》 （第三方包》）自己的包
logger = logging.getLogger('django')
# Create your views here.
# def register(request):
#     """
#     register page
#     :param request:
#     :return:
#     """
#     return render(request,'users/register.html')
# def login(request):
#     return render(request,'users/login.html')
#1.创建一个类
#2.创建get方法
#3.创建post方法
#4.获取前端传过来的参数
#5.校验参数
#6.将用户信息保存到数据库
#7.结果返回给前端
class RegisterView(View):
    """
    handle get request，render register page
    """
    def get(self, request):
        """
        :param request:
#       :return:
        创建get register page
        """
        return render(request, 'users/register.html')
    def post(self, request):
        """
        :param request:
#       :return:
        创建post
        """
        # 4.验证传过来的参数
        try:
            json_data = request.body
            if not json_data:
                return to_json_data(errno=Code.PARAMERR, errmsg='参数为空，请重新输入！')
            # 将json转化为dict
            #print(json_data.decode('utf8'))
            #print(type(json_data.decode('utf8')))
            dict_data = json.loads(json_data.decode('utf8'))
            # dict_data = json.loads(json_data)
        except Exception as e:
            logger.info('错误信息：\n{}'.format(e))
            return to_json_data(errno=Code.UNKOWNERR, errmsg=error_map[Code.UNKOWNERR])
        dict_data.update({'route_id': '0'})
        form = RegisterForm(data=dict_data)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            mobile = form.cleaned_data.get('mobile')
            print(password)
            user = Users.objects.create_user(username=username, password=password, mobile=mobile)
            # 处理session
            login(request, user)
            return to_json_data(errmsg="恭喜您，注册成功！")
        else:
            # 定义一个错误信息列表
            err_msg_list = []
            for item in form.errors.get_json_data().values():
                err_msg_list.append(item[0].get('message'))
            err_msg_str = '/'.join(err_msg_list)
            return to_json_data(errno=Code.PARAMERR, errmsg=err_msg_str)
class LoginView(View):
    """
    user login view
    router:/users/login
    #1.创建类
    """
    def get(self, request):
        """
        :param request:
        :return login page
        """
        return render(request, 'users/login.html')
    def post(self, request):
        """
        :param request:
        :return:
        """
        #2.获取前端数据
        json_data = request.body
        #print(json_data,type(json_data))
        #3.校验参数
        if not json_data:
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])
        # 将json转化为dict
        dict_data = json.loads(json_data.decode('utf8')) # 没有解码，会产生bug
        print(dict_data, type(dict_data))
        #4.用户登录，设置session
        form = LoginForm(data=dict_data, request=request)
        if form.is_valid():
            #5.返回前端
            return to_json_data(errmsg="恭喜您，登录成功！")
        else:
            # 定义一个错误信息列表
            err_msg_list = []
            for item in form.errors.get_json_data().values():
                err_msg_list.append(item[0].get('message'))
            err_msg_str = '/'.join(err_msg_list)  # 拼接错误信息为一个字符串
            return to_json_data(errno=Code.PARAMERR, errmsg=err_msg_str)
class LogoutView(View):
    """
    """
    def get(self, request):
        logout(request)
        return redirect(reverse("users:login"))


class ChangeView(View):
    """
    create changepassword view
    """
    def get(self, request):
        """
        :param request:
#       :return:
        创建get change page
        """
        return render(request, 'users/changepassword.html')
    def post(self, request):
        """
        :param request:
#       :return:
        创建post
        """
        # 验证传过来的参数
        try:
            json_data = request.body
            if not json_data:
                return to_json_data(errno=Code.PARAMERR, errmsg='参数为空，请重新输入！')
            # 将json转化为dict
            dict_data = json.loads(json_data.decode('utf8'))
        except Exception as e:
            logger.info('错误信息：\n{}'.format(e))
            return to_json_data(errno=Code.UNKOWNERR, errmsg=error_map[Code.UNKOWNERR])
        dict_data.update({'route_id':'1'})#加一验证字段 可区别 注册与修改密码功能的form验证
        form = RegisterForm(data=dict_data)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user_queryset = Users.objects.filter(Q(mobile=username) | Q(username=username))
            if user_queryset:
                user = user_queryset.first()
                # 判断手机号与用户手机号是否相同
                tel = dict_data.get('mobile')
                #print(user.mobile)
                if tel != user.mobile:
                    return to_json_data(errno=Code.DATAERR, errmsg="手机号与注册时不符！")
                if user.check_password(password):
                    return to_json_data(errno=Code.DATAEXIST,errmsg="新密码与旧密码相同！")
                else:
                    user.set_password(password)
                    user.save()
                    return to_json_data(errmsg="恭喜您，密码修改成功!")
            else:
                return to_json_data(errmsg="用户账号不存在，请重新输入")
        else:
            # 定义一个错误信息列表
            err_msg_list = []
            for item in form.errors.get_json_data().values():
                err_msg_list.append(item[0].get('message'))
            err_msg_str = '/'.join(err_msg_list)
            return to_json_data(errno=Code.PARAMERR, errmsg=err_msg_str)

templates/users/changepassword.html
{% extends 'base/base.html' %}
{% block title %}
修改登录密码
{% endblock %}
{% block link %}
  <link rel="stylesheet" href="/static/css/authPro/auth.css">
{% endblock %}
<!-- header start -->
<!-- header end -->
<!-- container start -->
{% block main_start %}
  <main id="container">
  <div class="register-contain">
    <div class="top-contain">
      <a href="{% url 'users:register' %}" class="please-register">< 去注册</a>
      <a href="{% url 'users:login' %}" class="login">立即登录 &gt;</a>
    </div>
    <form action="" method="post" class="form-contain">
      {% csrf_token %}
      <div class="form-item">
        <input type="text" id="user_name" placeholder="输入用户名或手机号" name="username" class="form-control" autocomplete="off">
      </div>
      <div class="form-item">
        <input type="password" id="old-password" placeholder="旧密码" name="old-password" class="form-control">
      </div>
      <div class="form-item">
        <input type="password" id="password" placeholder="新密码" name="password" class="form-control">
      </div>
      <div class="form-item">
        <input type="password" id="password-repeat" placeholder="确认新密码" name="password_repeat" class="form-control">
      </div>
      <div class="form-item">
        <input type="tel" id="mobile" placeholder="输入手机号" name="telephone" class="form-control" autocomplete="off" >
      </div>
      <div class="form-item">
        <input type="text" placeholder="输入图形验证码" name="captcha_graph" class="form-captcha" id="input_captcha">
        <a href="javascript:void(0);" class="captcha-graph-img">
          <img src="" alt="验证码" title="点击刷新">
        </a>
      </div>
      <div class="form-item">
        <input type="text" placeholder="输入短信验证码" name="sms_captcha" class="form-captcha" autocomplete="off">
        <a href="javascript:void(0);" class="sms-captcha" title="发送验证码">获取短信验证码</a>
      </div>
      <div class="form-item">
        <input type="submit" value="修改密码" class="register-btn" id="change-btn">
      </div>
    </form>
  </div>
</main>
{% endblock %}
<!-- container end -->
{% block side %}
{% endblock %}
<!-- footer start -->
<!-- footer end -->

{% block script %}
{#  <script src="/static/js/users/auth.js"></script>#}
  <script src="{% static 'js/users/change.js' %}"></script>
{% endblock %}

templates/users/login.html
{% extends 'base/base.html' %}
{% block link %}
    <link rel="stylesheet" href="/static/css/authPro/auth.css">
{% endblock %}
{% block title %}
    用户登录
{% endblock %}
<!-- header start -->
<!-- header end -->
<!-- container start -->
{% block main_start %}
   <main id="container">
    <div class="login-contain">
        <div class="top-contain">
      <h4 class="please-login">请登录</h4>
      <a href="{% url 'users:register' %}" class="register">立即注册 &gt;</a>
    </div>
        <form action="" method="post" class="form-contain">
            {% csrf_token %}
            <div class="form-item">
            <input type="tel" placeholder="请输入手机号" name="telephone" class="form-control" autocomplete="off">
          </div>
          <div class="form-item">
            <input type="password" placeholder="请输入密码" name="password" class="form-control">
          </div>
          <div class="form-item clearfix">
            <label>
              <input type="checkbox" name="remember">
              <span>记住我</span>
            </label>
            <a href="javascript:void(0);" class="forget-password">忘记密码?</a>
          </div>
          <div class="form-item" style="text-align: right">
            <a href="{% url 'users:change' %}">修改密码 ></a>
          </div>
          <div class="form-login">
            <input type="submit" value="登录" class="login-btn">
          </div>
        </form>
    </div>
  </main>
{% endblock %}
<!-- container end -->
{% block side %}
{% endblock %}
<!-- footer start -->
<!-- footer end -->
{% block script %}
{#  <script src="/static/js/users/auth.js"></script>#}
  <script src="{% static 'js/users/login.js' %}"></script>
{% endblock %}

templates/users/register.html
{% extends 'base/base.html' %}
{% block title %}
用户注册
{% endblock %}
{% block link %}
  <link rel="stylesheet" href="/static/css/authPro/auth.css">
{% endblock %}
<!-- header start -->
<!-- header end -->
<!-- container start -->
{% block main_start %}
  <main id="container">
  <div class="register-contain">
    <div class="top-contain">
      <h4 class="please-register">请注册</h4>
      <a href="{% url 'users:login' %}" class="login">立即登录 &gt;</a>
    </div>
    <form action="" method="post" class="form-contain">
      {% csrf_token %}
      <div class="form-item">
        <input type="text" id="user_name" placeholder="请输入用户名" name="username" class="form-control" autocomplete="off">
      </div>
      <div class="form-item">
        <input type="password" id="password" placeholder="请输入密码" name="password" class="form-control">
      </div>
      <div class="form-item">
        <input type="password" placeholder="请输入确认密码" name="password_repeat" class="form-control">
      </div>
      <div class="form-item">
        <input type="tel" id="mobile" placeholder="请输入手机号" name="telephone" class="form-control" autocomplete="off" >
      </div>
      <div class="form-item">
        <input type="text" placeholder="请输入图形验证码" name="captcha_graph" class="form-captcha" id="input_captcha">
        <a href="javascript:void(0);" class="captcha-graph-img">
          <img src="" alt="验证码" title="点击刷新">
        </a>
      </div>
      <div class="form-item">
        <input type="text" placeholder="请输入短信验证码" name="sms_captcha" class="form-captcha" autocomplete="off">
        <a href="javascript:void(0);" class="sms-captcha" title="发送验证码">获取短信验证码</a>
      </div>
      <div class="form-item" style="text-align: right">
        <a href="{% url 'users:change' %}">修改密码 ></a>
      </div>
      <div class="form-item">
        <input type="submit" value="立即注册" class="register-btn">
      </div>

    </form>
  </div>
</main>
{% endblock %}
<!-- container end -->
{% block side %}
{% endblock %}
<!-- footer start -->
<!-- footer end -->

{% block script %}
{#  <script src="/static/js/users/auth.js"></script>#}
  <script src="{% static 'js/users/auth.js' %}"></script>
{% endblock %}