apps/doc/urls.py
from django.urls import path
from . import views
# app的名字
app_name = 'doc'
urlpatterns = [
    # path('doc_down',views.doc_down,name='doc_down'),
    path('', views.doc_index, name='index'),
    path('<int:doc_id>/', views.DocDownload.as_view(), name='doc_download'),
]

myblog/urls.py
# from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_index
urlpatterns = [
   # path('admin/', admin.site.urls),
   #  path('',home_index),
    path('',include('news.urls')),
    path('users/',include('users.urls')),
    path('course/',include('course.urls')),
    path('docs/',include('doc.urls')),
    path('',include('verifications.urls')),
    path('admin/',include('admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/doc/models.py
from django.db import models
from utils.models import ModelBase

# Create your models here.
class Doc(ModelBase):
    """create doc view
    """
    file_url = models.URLField(verbose_name="文件url", help_text="文件url")
    title = models.CharField(max_length=150, verbose_name="文档标题", help_text="文档标题")
    desc = models.TextField(verbose_name="文档描述", help_text="文档描述")
    image_url = models.URLField(default="", verbose_name="图片url", help_text="图片url")
    author = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        db_table = "tb_docs"   # 指明数据库表名
        verbose_name = "文档"    # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.title

apps/doc/views.py
import requests
import logging
import urllib3

from django.shortcuts import render
from django.http import FileResponse, Http404
from django.utils.encoding import escape_uri_path
from django.views import View
from django.conf import settings

from .models import Doc

# 导入日志器
logger = logging.getLogger('django')

# Create your views here.
def doc_index(request):
    """
    download doc
    :param request:
    :return:
    """
    docs = Doc.objects.defer('author', 'create_time', 'update_time', 'is_delete').filter(is_delete=False)
    navId = 2
    return render(request, 'doc/docDownload.html', locals())


class DocDownload(View):
    """
    create doc download view
    route:/docs/<int:doc_id>/
    """
    def get(self, request, doc_id):
        doc = Doc.objects.only('file_url').filter(is_delete=False, id=doc_id).first()
        if doc:
            doc_url = doc.file_url
            doc_url = settings.SITE_DOMAIN_PORT + doc_url if not doc_url.startswith('http') else doc_url
            doc_name = doc.title
            try:
                res = FileResponse(requests.get(doc_url, stream=True))#stream 参数 第一次请求不会下载 优化
                # 仅测试的话可以这样子设置
                # res = FileResponse(open(doc.file_url, 'rb'))
            except Exception as e:
                logger.info("获取文档内容出现异常：\n{}".format(e))
                raise Http404("文档下载异常！")

            ex_name = doc_url.split('.')[-1]
            # https://stackoverflow.com/questions/23714383/what-are-all-the-possible-values-for-http-content-type-header
            # http://www.iana.org/assignments/media-types/media-types.xhtml#image
            if not ex_name:
                raise Http404("文档url异常！")
            else:
                ex_name = ex_name.lower()

            if ex_name == "pdf":
                res["Content-type"] = "application/pdf"
            elif ex_name == "zip":
                res["Content-type"] = "application/zip"
            elif ex_name == "doc":
                res["Content-type"] = "application/msword"
            elif ex_name == "xls":
                res["Content-type"] = "application/vnd.ms-excel"
            elif ex_name == "docx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            elif ex_name == "ppt":
                res["Content-type"] = "application/vnd.ms-powerpoint"
            elif ex_name == "pptx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation"

            else:
                raise Http404("文档格式不正确！")
            final_filename = doc.title + '.'+ ex_name
            #http://192.168.192.128:8888/group1/M00/00/00/wKjAgFxa5NqAM0x8ALVDjXyBkGA890.pdf
            # doc_filename = escape_uri_path(doc_url.split('/')[-1])
            doc_filename = escape_uri_path(final_filename)
            # 设置为inline，会直接打开 attachment 不打开 提示下载
            # res["Content-Disposition"] = "inline; filename={}".format(doc_url.split('/')[-1])
            res["Content-Disposition"] = "attachment; filename*=UTF-8''{}".format(doc_filename)
            return res

        else:
            raise Http404("文档不存在！")

# def doc_down(request):
#     """
#     docDownload page
#         :param request:
#         :return:
#     """
#     return render(request,'doc/docDownload.html')

templates/doc/docDownload.html
{% extends 'base/base.html' %}
{% block link %}
  <link rel="stylesheet" href="../../static/css/doc/docDownload.css">
{% endblock %}
{% block title %}
下载文件
{% endblock %}
<!-- header start -->
<!-- header end -->
<!-- main start -->
{% block main_start %}
  <main id="main">
    <div class="w1200 clearfix">
        <!-- main-contain start  -->
        <div class="main-contain ">
            <div class="banner">
                <img src="https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1802845035,3786939119&fm=26&gp=0.jpg"
                     alt="">
            </div>
            <div class="pay-doc-contain">
                <ul class="pay-list">
                    {% for doc in docs %}
                        <li class="pay-item">
{#                            <div class="pay-img doc"></div>#}
                            <img src="{{ doc.image_url }}" alt="{{ doc.title }}" class="pay-img doc">
                            <div class="pay-contain">
                                <p class="pay-title">{{ doc.title }}</p>
                                <p class="pay-desc">{{ doc.desc }}</p>
                                <a href="{% url 'doc:doc_download' doc.id %}" class="pay-price">下载</a>
                            </div>
                        </li>
                    {% endfor %}
{#                    <li class="pay-item">#}
{#                        <div class="pay-img doc"></div>#}
{#                        <div class="pay-contain">#}
{#                            <p class="pay-title">流畅的Python</p>#}
{#                            <p class="pay-desc">【本书特色】#}
{##}
{#                                本书由奋战在Python开发一线近20年的Luciano Ramalho执笔，Victor Stinner、Alex#}
{#                                Martelli等Python大咖担纲技术审稿人，从语言设计层面剖析编程细节，兼顾Python 3和Python#}
{#                                2，告诉你Python中不亲自动手实践就无法理解的语言陷阱成因和解决之道，教你写出风格地道的Python代码。</p>#}
{##}
{#                            <!-- /www/?xxx -->#}
{#                            <a href="#" class="pay-price">下载</a>#}
{#                        </div>#}
{#                    </li>#}
{##}
{#                    <li class="pay-item">#}
{#                        <div class="pay-img doc"></div>#}
{#                        <div class="pay-contain">#}
{#                            <p class="pay-title">深入Flask</p>#}
{#                            <p class="pay-desc">深入Flask，强烈推荐！</p>#}
{##}
{#                            <!-- /www/?xxx -->#}
{#                            <a href="#" class="pay-price">下载</a>#}
{#                        </div>#}
{#                    </li>#}

                </ul>
            </div>
        </div>
        <!-- main-contain  end -->
        <!-- side start -->
        {% block side %}
          {{ block.super }}
        {% endblock %}
        <!-- side end -->
    </div>
  </main>
{% endblock %}
<!-- main end -->
<!-- footer start -->
<!-- footer end -->